#!/usr/bin/env python3
"""Share the project ZIP with devices on the same local network."""

from __future__ import annotations

import argparse
import hashlib
import secrets
import socket
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote, urlsplit


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FILE = PROJECT_ROOT / "Github_bounty_dispenser-main.zip"
COPY_BUFFER_SIZE = 1024 * 1024


def local_ip() -> str:
    """Find the address used for local-network traffic without sending data."""
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(("10.255.255.255", 1))
        return str(probe.getsockname()[0])
    except OSError:
        return "127.0.0.1"
    finally:
        probe.close()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(COPY_BUFFER_SIZE):
            digest.update(chunk)
    return digest.hexdigest()


def make_handler(shared_file: Path, download_path: str):
    class DownloadHandler(BaseHTTPRequestHandler):
        server_version = "ProjectLANShare/1.0"

        def do_GET(self) -> None:  # noqa: N802
            self._respond(include_body=True)

        def do_HEAD(self) -> None:  # noqa: N802
            self._respond(include_body=False)

        def _respond(self, *, include_body: bool) -> None:
            if urlsplit(self.path).path != download_path:
                self.send_error(404, "Download link not found")
                return

            size = shared_file.stat().st_size
            self.send_response(200)
            self.send_header("Content-Type", "application/zip")
            self.send_header("Content-Length", str(size))
            self.send_header(
                "Content-Disposition",
                f"attachment; filename*=UTF-8''{quote(shared_file.name)}",
            )
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            if not include_body:
                return

            with shared_file.open("rb") as source:
                while chunk := source.read(COPY_BUFFER_SIZE):
                    self.wfile.write(chunk)

        def log_message(self, message: str, *args: object) -> None:
            print(f"{self.client_address[0]} - {message % args}")

    return DownloadHandler


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Temporarily share one ZIP file on the local network."
    )
    parser.add_argument(
        "--file",
        type=Path,
        default=DEFAULT_FILE,
        help=f"ZIP to share (default: {DEFAULT_FILE})",
    )
    parser.add_argument(
        "--host",
        default="0.0.0.0",
        help="Address to bind (default: all local interfaces)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8765,
        help="TCP port to use (default: 8765)",
    )
    parser.add_argument(
        "--token",
        help="Optional fixed URL token; a random token is generated by default",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    shared_file = args.file.expanduser().resolve()
    if not shared_file.is_file():
        raise SystemExit(f"File not found: {shared_file}")
    if shared_file.suffix.lower() != ".zip":
        raise SystemExit("Refusing to share a non-ZIP file")
    if not 1 <= args.port <= 65535:
        raise SystemExit("Port must be between 1 and 65535")

    token = args.token or secrets.token_urlsafe(18)
    download_path = f"/download/{token}"
    server = ThreadingHTTPServer(
        (args.host, args.port),
        make_handler(shared_file, download_path),
    )
    address = local_ip() if args.host == "0.0.0.0" else args.host
    url = f"http://{address}:{server.server_port}{download_path}"

    print(f"Sharing: {shared_file}")
    print(f"Size: {shared_file.stat().st_size:,} bytes")
    print(f"SHA-256: {sha256(shared_file)}")
    print(f"Download URL: {url}")
    print("Keep this terminal open. Press Ctrl+C to stop sharing.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nSharing stopped.")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
